### ISSUE TITLE
Unexpected token when importing VueFuse

### ISSUE THREAD

**Issue by kgnfth** [shayneo/vue-fuse#82]
like the title says i am getting `Unexpected token '<'`

**Comment by shayneo** [comment]
could you show me what the code looks like for your import?

**Comment by kgnfth** [comment]
i use it in nuxt.js as a plugin

```
import Vue from 'vue'
import VueFuse from 'vue-fuse'

Vue.use(VueFuse)
```

this code gives 
![image](https://user-images.githubusercontent.com/73314940/108128267-c2cf8d80-70ac-11eb-8214-994b040f4e6f.png)

**Comment by shayneo** [comment]
The global registration wont work as of version 3

Instead you should be able to import into a component and register as a component, like so

```
<script>
import VueFuse from 'vue-fuse'

export default {
  components: {
    VueFuse,
  },
}
</script>
```

**Comment by rylax** [comment]
Also using server-side Nuxt.js with: 
```// nuxt.config.js
mode: 'universal'
target: 'server'
```
and even with the depicted component registration I get the same error syntax error "Unexpected token '<'" The problem seems to be associated with SSR. 

Tried out rendering only client-side:
```// nuxt.config.js
mode: 'spa'
target: 'static'
```
and this strangely works. Any reason why ```target: 'server'``` seems to break and what we can do about it?
