### ISSUE TITLE
Syntax Error when using 'target: server' with Nuxt.js

### ISSUE THREAD

**Issue by rylax** [shayneo/vue-fuse#97]
Issue related to: https://github.com/shayneo/vue-fuse/issues/82

When using server-side Nuxt.js with: 
```// nuxt.config.js
mode: 'universal'
target: 'server'
```
with component registration:
```
<script>
import VueFuse from 'vue-fuse'

export default {
  components: {
    VueFuse,
  },
}
</script>
```
 I get the syntax error **"Unexpected token '<'"** 

The problem seems to be associated with SSR. Tried out rendering only client-side:
```// nuxt.config.js
mode: 'spa'
target: 'static'
```
and this strangely works. Any reason why ```target: 'server'``` seems to break and what we can do about it?

**Comment by shayneo** [comment]
I think the problem is that the module ships the raw `.vue` file as opposed to a compiled js version. This was my overly simple technique to supporting both Vue2 and Vue3.  To get this to work I think I'd need to leverage something like [vue-demi](https://www.npmjs.com/package/vue-demi), which might take me a while to get around to.

Until then, I HIGHLY recommend taking a look at the source-code, as you can easily drop Fuse.js into your project directly and build your own fuzzy search functionality. This package doesn't do anything special, just a convenience wrapper around Fuse.

**Comment by scottyzen** [comment]
I had the same issue but got it to work by wrapping the client-only component around it.
```javascript
<client-only>
    <VueFuse />
</client-only>
```

Any the import the VueFuse component like this.
```javascript
export default {
    components: {
        VueFuse: () => import('vue-fuse')
    }
}
```

**Comment by rylax** [comment]
> ```js
>   VueFuse: () => import('vue-fuse')
> ```

While this approach did work for me in the end, I have just noticed that it created a huge memory leak. Trying to find a workaround now.

**Comment by hacknug** [comment]
> > ```js
> >   VueFuse: () => import('vue-fuse')
> > ```
> 
> While this approach did work for me in the end, I have just noticed that it created a huge memory leak. Trying to find a workaround now.

Have you tried importing the component on a client-only plugin? That usually solves all the similar issues I encounter.
